run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gofmt
    - goimports
    - misspell
    - unconvert
    - gocritic
    - errname
    - errorlint

linters-settings:
  goimports:
    local-prefixes: leetcode-spaced-repetition
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  errcheck:
    check-type-assertions: true
  govet:
    enable-all: true

issues:
  exclude-use-default: false
  exclude-dirs-use-default: true
  max-issues-per-linter: 0
  max-same-issues: 0
