services:
  db:
    container_name: leetcode-buddy-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network
  
  app:
    container_name: leetcode-buddy-app-frontend
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend/
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true 
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 5173:5173
    networks:
      - app-network
    restart: unless-stopped


  api:
    container_name: leetcode-buddy-app-api
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - app-network
    restart: always

  db-seeding:
    build:
      dockerfile: Dockerfile.data-seeding
      context: ./
    depends_on:
      - db
    networks:
      - app-network
    restart: "no"
 
networks:
  app-network:
    driver: bridge

volumes:
  pgdata: