# Build stage
FROM golang:1.26-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod tidy
COPY . .
RUN go build -o leetcode-spaced-repetition-migrations applications/migrations/main.go

# Runtime stage
FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /app/leetcode-spaced-repetition-migrations .
ENTRYPOINT ["./leetcode-spaced-repetition-migrations"]
